apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.service.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: fadc-k8s-ctrl
  ports:
    - port: {{ .Values.webhook.service.port }}
      targetPort: {{ .Values.webhook.service.targetPort }}

