kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fadc-k8s-ctrl.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "endpoints", "secrets", "namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - extensions
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
{{- if eq .Values.parameters.openshiftRouteSupport "yes" }}
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes/status
  verbs:
  - get
  - list
  - watch
  - update
{{- end }}
- apiGroups: ["fadk8sctrl.fortinet.com"]
  resources: ["virtualservers", "remoteservers", "hosts", "fortiadcvirtualserverpolicies", "fortiadcgatewayparameters"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["fadk8sctrl.fortinet.com"]
  resources: ["virtualservers/status", "remoteservers/status", "hosts/status", "fortiadcgatewayparameters/status", "fortiadcvirtualserverpolicies/status"]
  verbs: ["get", "update", "patch"]
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gatewayclasses
  - gateways
  - httproutes
  - tcproutes
  - udproutes
  - tlsroutes
  - referencegrants
  verbs: ["get", "list", "watch"]
- apiGroups: ["gateway.networking.k8s.io"]
  resources:
  - gatewayclasses/status
  - gateways/status
  - httproutes/status
  - tcproutes/status
  - udproutes/status
  - tlsroutes/status
  verbs: ["update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "fadc-k8s-ctrl.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "fadc-k8s-ctrl.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "fadc-k8s-ctrl.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
