apiVersion: fadk8sctrl.fortinet.com/v1alpha2
kind: VirtualServer
metadata:
  name: tcp-postgres-ssl-virtualserver
  annotations: {
    "fortiadc-ip" : "172.23.133.110",
    "fortiadc-login" : "fad-login",
    "fortiadc-ctrl-log" : "enable",
    "fortiadc-admin-port": "443"
   }
spec:
  addressType: ipv4
  address: 192.168.1.108
  port: 5432
  interface: port3
  loadBalanceProfile: LB_PROF_TCP
  loadBalanceMethod: LB_METHOD_ROUND_ROBIN
  natSourcePoolList:
    - name: socat
  contentRoutings:
    - name: route1
      type: l4-content-routing
      sourceAddressType: ipv4
      sourceAddress: 192.168.1.0/24
      realServerPool:
        service: postgres-ssl-service
        servicePort: 5432
        serviceNamespace: default
  vdom: root

