apiVersion: v1
kind: Pod
metadata:
  name: tcp-echo-server
  labels:
    app: tcp-echo-server
spec:
  containers:
    - name: tcp-echo-server
      image: alpine/socat
      args: ["tcp-l:12345,reuseaddr,fork", "system:/bin/cat"]
      ports:
        - containerPort: 12345
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-echo-service
  annotations: {
    "health-check-ctrl" : "enable",
    "health-check-relation" : "OR",
    "health-check-list" : "LB_HLTHCK_ICMP",
    "real-server-ssl-profile" : "NONE",
    "overlay_tunnel" : "k8s"
  }
spec:
  ports:
  - port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: tcp-echo-server

